site_name: "mlregistry"

theme:
  name: "readthedocs"

nav:
  - Home: index.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "google"  # or "restructuredtext"